Support shapeless coproduct fields with default values
Support for schema generation for fields with shapeless Coproduct type
and default value.

Note that we only support `Inl(...)`, not `Inr(...(Inl(...)))`, because
"the type of the default value must match the first element of the
union" (quoted from the Avro spec).

Without the `Inl(x)` case added to `DefaultResolver`, the pattern match
falls into the `Product` case and the test fails with:

```
org.apache.avro.AvroTypeException: Invalid default for field u: {"head":123} not a ["int","string","boolean",{"type":"record","name":"Gimble","namespace":"com.sksamuel.avro4s.schema","fields":[{"name":"x","type":"string"}]}]
```